from . import recruitment_request
from . import recruitment_request_line
from . import major
from . import applicant
from . import recruitment_session
from . import recruitment_session_line
from . import interview
from . import interview_line
from . import mail_invite_applicant
from . import interview_questions
from . import job_position
from . import certificate
from . import experience
from . import search_applicant_criteria
from . import search_applicant_result
from . import applicant_references
from . import applicant_degree
from . import foreign_language
from . import family_relationship
from . import source_model
from . import job
from . import applicant_call_history
from . import applicant_status
from . import hr_employee_inherit
from . import import_applicant
from . import inherit_mail_compose_message
from . import applicant_question